## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file error_propogation.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_122 = Integer(122); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_168 = Integer(168); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_161 = Integer(161); _sage_const_175 = Integer(175)## This file (error_propogation.sagetex.sage) was *autogenerated* from error_propogation.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('error_propogation', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_122 
_st_.blockbegin()
try:
 def trilateration_eqn_npods(n):
     if n < _sage_const_3 :
         return "You can't TRIlaterate with less than 3, dummy"
 
     x, y = var('x', 'y')
 
     x_loc = list(var('x_{}'.format(i)) for i in range(_sage_const_1 , n + _sage_const_1 ))
     y_loc = list(var('y_{}'.format(i)) for i in range(_sage_const_1 , n + _sage_const_1 ))
     r = list(var('r_{}'.format(i)) for i in range(_sage_const_1 , n + _sage_const_1 ))
 
     if n == _sage_const_3 :
         distance_equations = []
 
         for i in range(_sage_const_1 , n):
             distance_equations.append(-_sage_const_2  * x * (x_loc[i - _sage_const_1 ] - x_loc[i]) \
                                       -_sage_const_2  * y * (y_loc[i - _sage_const_1 ] - y_loc[i]) == \
                                       r[i - _sage_const_1 ] ** _sage_const_2  - r[i] ** _sage_const_2 \
                                       - x_loc[i - _sage_const_1 ] ** _sage_const_2  + x_loc[i] ** _sage_const_2 \
                                       - y_loc[i - _sage_const_1 ]** _sage_const_2  + y_loc[i] ** _sage_const_2 )
 
         res = solve(distance_equations, x, y)
         x_func = res[_sage_const_0 ][_sage_const_0 ].right()
         y_func = res[_sage_const_0 ][_sage_const_1 ].right()
 
         return x_func.simplify_full(), y_func.simplify_full()
 
     if n > _sage_const_3 :
         A = matrix(SR, n - _sage_const_1 , _sage_const_2 )
         b = matrix(SR, n - _sage_const_1 , _sage_const_1 )
 
         for i in range(_sage_const_1 , n):
             A[i-_sage_const_1 ] = (-_sage_const_2  * (x_loc[i - _sage_const_1 ] - x_loc[i]), - _sage_const_2  * (y_loc[i - _sage_const_1 ] - y_loc[i]))
             b[i-_sage_const_1 ] = r[i - _sage_const_1 ] ** _sage_const_2  - r[i] ** _sage_const_2  - x_loc[i - _sage_const_1 ]** _sage_const_2  \
                      + x_loc[i] ** _sage_const_2  - y_loc[i - _sage_const_1 ]** _sage_const_2  + y_loc[i] ** _sage_const_2 
 
         x_hat = (A.T * A).inverse() * A.T * b
 
         return x_hat[_sage_const_0 ].simplify_full(), x_hat[_sage_const_1 ].simplify_full()
except:
 _st_.goboom(_sage_const_161 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_0 , latex(trilateration_eqn_npods(_sage_const_3 )[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_1 , latex(trilateration_eqn_npods(_sage_const_3 )[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_0 , latex(trilateration_eqn_npods(_sage_const_3 )[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_1 , latex(trilateration_eqn_npods(_sage_const_3 )[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_175 
 _st_.inline(_sage_const_2 , latex(trilateration_eqn_npods(_sage_const_4 )[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_175 )
try:
 _st_.current_tex_line = _sage_const_175 
 _st_.inline(_sage_const_3 , latex(trilateration_eqn_npods(_sage_const_4 )[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_175 )
try:
 _st_.current_tex_line = _sage_const_175 
 _st_.inline(_sage_const_2 , latex(trilateration_eqn_npods(_sage_const_4 )[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_175 )
try:
 _st_.current_tex_line = _sage_const_175 
 _st_.inline(_sage_const_3 , latex(trilateration_eqn_npods(_sage_const_4 )[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_175 )
_st_.endofdoc()

