## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file trilateration.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_261 = Integer(261); _sage_const_97 = Integer(97); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_201 = Integer(201); _sage_const_28 = Integer(28); _sage_const_6p4 = RealNumber('6.4'); _sage_const_8p2 = RealNumber('8.2'); _sage_const_67 = Integer(67); _sage_const_87 = Integer(87); _sage_const_p64 = RealNumber('.64'); _sage_const_157 = Integer(157); _sage_const_175 = Integer(175); _sage_const_151 = Integer(151); _sage_const_0p5 = RealNumber('0.5'); _sage_const_191 = Integer(191); _sage_const_198 = Integer(198); _sage_const_217 = Integer(217); _sage_const_p82 = RealNumber('.82'); _sage_const_278 = Integer(278); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_14 = Integer(14); _sage_const_275 = Integer(275); _sage_const_18 = Integer(18); _sage_const_53 = Integer(53); _sage_const_p9 = RealNumber('.9'); _sage_const_109 = Integer(109); _sage_const_181 = Integer(181); _sage_const_167 = Integer(167); _sage_const_104 = Integer(104); _sage_const_271 = Integer(271); _sage_const_143 = Integer(143); _sage_const_225 = Integer(225); _sage_const_227 = Integer(227)## This file (trilateration.sagetex.sage) was *autogenerated* from trilateration.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('trilateration', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_53 
_st_.blockbegin()
try:
 x, x_1, x_2, x_3, y, y_1, y_2, y_3 = var('x', 'x_1', 'x_2', 'x_3', 'y', 'y_1', 'y_2', 'y_3')
 
 r_1, r_2, r_3 = var('r_1', 'r_2', 'r_3')
 
 distance1 = ( -_sage_const_2  * x_1 + _sage_const_2  * x_2) * x + (-_sage_const_2  * y_1 + _sage_const_2  * y_2) * y == r_1 ** _sage_const_2  - r_2 ** _sage_const_2  - x_1 ** _sage_const_2  + x_2 ** _sage_const_2  - y_1 ** _sage_const_2  + y_2 ** _sage_const_2 
 distance2 = ( -_sage_const_2  * x_2 + _sage_const_2  * x_3) * x + (-_sage_const_2  * y_2 + _sage_const_2  * y_3) * y == r_2 ** _sage_const_2  - r_3 ** _sage_const_2  - x_2 ** _sage_const_2  + x_3 ** _sage_const_2  - y_2 ** _sage_const_2  + y_3 ** _sage_const_2 
 
 res = solve([distance1, distance2], x, y)
 
 x_func = res[_sage_const_0 ][_sage_const_0 ].right()
 x = x_func
 y_func = res[_sage_const_0 ][_sage_const_1 ].right()
 y = y_func
except:
 _st_.goboom(_sage_const_67 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_0 , latex(x))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_1 , latex(y))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_0 , latex(x))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_1 , latex(y))
except:
 _st_.goboom(_sage_const_87 )
_st_.current_tex_line = _sage_const_97 
_st_.blockbegin()
try:
     def eval(thing):
         return thing(x_1 = _sage_const_12 , y_1 = _sage_const_14 , x_2 = _sage_const_18 , y_2 = _sage_const_4 , x_3 = _sage_const_28 ,
                      y_3 = _sage_const_8 , r_1 = _sage_const_9 , r_2 = _sage_const_6p4 , r_3 = _sage_const_8p2 )
 
     x_particular = eval(x)
     y_particular = eval(y)
except:
 _st_.goboom(_sage_const_104 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.inline(_sage_const_2 , latex(x_particular.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_109 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.inline(_sage_const_3 , latex(y_particular.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_109 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.inline(_sage_const_2 , latex(x_particular.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_109 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.inline(_sage_const_3 , latex(y_particular.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_109 )
_st_.current_tex_line = _sage_const_143 
_st_.blockbegin()
try:
     g_r1 = diff(x_func, r_1)
     g_r2 = diff(x_func, r_2)
     g_r3 = diff(x_func, r_3)
 
     h_r1 = diff(y_func, r_1)
     h_r2 = diff(y_func, r_2)
     h_r3 = diff(y_func, r_3)
except:
 _st_.goboom(_sage_const_151 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_4 , latex(g_r1))
except:
 _st_.goboom(_sage_const_157 )
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_5 , latex(g_r2))
except:
 _st_.goboom(_sage_const_157 )
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_6 , latex(g_r3))
except:
 _st_.goboom(_sage_const_157 )
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_4 , latex(g_r1))
except:
 _st_.goboom(_sage_const_157 )
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_5 , latex(g_r2))
except:
 _st_.goboom(_sage_const_157 )
try:
 _st_.current_tex_line = _sage_const_157 
 _st_.inline(_sage_const_6 , latex(g_r3))
except:
 _st_.goboom(_sage_const_157 )
_st_.current_tex_line = _sage_const_167 
_st_.blockbegin()
try:
     g_r1 = eval(g_r1)
     g_r2 = eval(g_r2)
     g_r3 = eval(g_r3)
 
     h_r1 = eval(h_r1)
     h_r2 = eval(h_r2)
     h_r3 = eval(h_r3)
except:
 _st_.goboom(_sage_const_175 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_7 , latex(g_r1.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_8 , latex(g_r2.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_9 , latex(g_r3.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_7 , latex(g_r1.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_8 , latex(g_r2.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
try:
 _st_.current_tex_line = _sage_const_181 
 _st_.inline(_sage_const_9 , latex(g_r3.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_181 )
_st_.current_tex_line = _sage_const_191 
_st_.blockbegin()
try:
     sigma_r1 = _sage_const_p9 
     sigma_r2 = _sage_const_p64 
     sigma_r3 = _sage_const_p82 
 
     sigma_x = sqrt(g_r1 ** _sage_const_2  * sigma_r1 ** _sage_const_2  + g_r2 ** _sage_const_2  * sigma_r2 ** _sage_const_2  + g_r3 ** _sage_const_2   * sigma_r3 ** _sage_const_2 )
     sigma_y = sqrt(h_r1 ** _sage_const_2  * sigma_r1 ** _sage_const_2  + h_r2 ** _sage_const_2  * sigma_r2 ** _sage_const_2  + h_r3 ** _sage_const_2   * sigma_r3 ** _sage_const_2 )
except:
 _st_.goboom(_sage_const_198 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_201 
 _st_.inline(_sage_const_10 , latex(sigma_x.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_201 )
try:
 _st_.current_tex_line = _sage_const_201 
 _st_.inline(_sage_const_11 , latex(sigma_y.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_201 )
_st_.current_tex_line = _sage_const_217 
_st_.blockbegin()
try:
     sigma_x1 = _sage_const_0p5 
     sigma_x2 = _sage_const_0p5 
     sigma_x3 = _sage_const_0p5 
 
     sigma_y1 = _sage_const_0p5 
     sigma_y2 = _sage_const_0p5 
     sigma_y3 = _sage_const_0p5 
except:
 _st_.goboom(_sage_const_225 )
_st_.blockend()
_st_.current_tex_line = _sage_const_227 
_st_.blockbegin()
try:
     # Differentiate
     g_x1 = diff(x_func, x_1)
     g_x2 = diff(x_func, x_2)
     g_x3 = diff(x_func, x_3)
 
     g_y1 = diff(x_func, y_1)
     g_y2 = diff(x_func, y_2)
     g_y3 = diff(x_func, y_3)
 
     h_x1 = diff(y_func, x_1)
     h_x2 = diff(y_func, x_2)
     h_x3 = diff(y_func, x_3)
 
     h_y1 = diff(y_func, y_1)
     h_y2 = diff(y_func, y_2)
     h_y3 = diff(y_func, y_3)
 
     # Evaluate
     g_x1 = eval(g_x1)
     g_x2 = eval(g_x2)
     g_x3 = eval(g_x3)
 
     g_y1 = eval(g_y1)
     g_y2 = eval(g_y2)
     g_y3 = eval(g_y3)
 
     h_x1 = eval(h_x1)
     h_x2 = eval(h_x2)
     h_x3 = eval(h_x3)
 
     h_y1 = eval(h_y1)
     h_y2 = eval(h_y2)
     h_y3 = eval(h_y3)
except:
 _st_.goboom(_sage_const_261 )
_st_.blockend()
_st_.current_tex_line = _sage_const_271 
_st_.blockbegin()
try:
     sigma_x = sqrt(g_r1 ** _sage_const_2  * sigma_r1 ** _sage_const_2  + g_r2 ** _sage_const_2  * sigma_r2 ** _sage_const_2  + g_r3 ** _sage_const_2   * sigma_r3 ** _sage_const_2  + g_x1 ** _sage_const_2  * sigma_x1 ** _sage_const_2  + g_x2 ** _sage_const_2  * sigma_x2 ** _sage_const_2  + g_x3 ** _sage_const_2  * sigma_x3 ** _sage_const_2  + g_y1 ** _sage_const_2  * sigma_y1 ** _sage_const_2  + g_y2 ** _sage_const_2  * sigma_x2 ** _sage_const_2  + g_y3 ** _sage_const_2  * sigma_x3 ** _sage_const_2 )
 
     sigma_y = sqrt(h_r1 ** _sage_const_2  * sigma_r1 ** _sage_const_2  + h_r2 ** _sage_const_2  * sigma_r2 ** _sage_const_2  + h_r3 ** _sage_const_2   * sigma_r3 ** _sage_const_2  + h_x1 ** _sage_const_2  * sigma_x1 ** _sage_const_2  + h_x2 ** _sage_const_2  * sigma_x2 ** _sage_const_2  + h_x3 ** _sage_const_2  * sigma_x3 ** _sage_const_2  + h_y1 ** _sage_const_2  * sigma_y1 ** _sage_const_2  + h_y2 ** _sage_const_2  * sigma_x2 ** _sage_const_2  + h_y3 ** _sage_const_2  * sigma_x3 ** _sage_const_2 )
except:
 _st_.goboom(_sage_const_275 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_278 
 _st_.inline(_sage_const_12 , latex(sigma_x.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_278 )
try:
 _st_.current_tex_line = _sage_const_278 
 _st_.inline(_sage_const_13 , latex(sigma_y.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_278 )
_st_.endofdoc()

